# Comprobacion del modulo

In [114]:
#importar modulo propio
from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks/modulos')
import ML_V2 as ml
# importar librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [115]:
# cargar los datos de Seaborn
iris = sns.load_dataset("iris")
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [116]:
# extraer matriz de características y vector de etiquetas
X = iris.values[:100,2:4]
y = iris.values[:,-1]
iris.species.replace(['setosa','versicolor','virginica'],[0,1,2], inplace=True) #cambiar a etiquetas numericas
y=iris.values[:100,-1].astype('int32')
X.shape, y.shape

<ipython-input-116-3256b869b20e>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris.species.replace(['setosa','versicolor','virginica'],[0,1,2], inplace=True) #cambiar a etiquetas numericas
<ipython-input-116-3256b869b20e>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  iris.species.replace(['se

((100, 2), (100,))

In [117]:
#cambiar a etiquetas numericas los valores para y
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [118]:
#normalizar con sklearn
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_norm = scaler.fit_transform(X)

In [119]:
X_norm

array([[-1.01297765, -1.04211089],
       [-1.01297765, -1.04211089],
       [-1.08231219, -1.04211089],
       [-0.94364311, -1.04211089],
       [-1.01297765, -1.04211089],
       [-0.80497402, -0.68644165],
       [-1.01297765, -0.86427627],
       [-0.94364311, -1.04211089],
       [-1.01297765, -1.04211089],
       [-0.94364311, -1.21994552],
       [-0.94364311, -1.04211089],
       [-0.87430856, -1.04211089],
       [-1.01297765, -1.21994552],
       [-1.22098127, -1.21994552],
       [-1.15164673, -1.04211089],
       [-0.94364311, -0.68644165],
       [-1.08231219, -0.68644165],
       [-1.01297765, -0.86427627],
       [-0.80497402, -0.86427627],
       [-0.94364311, -0.86427627],
       [-0.80497402, -1.04211089],
       [-0.94364311, -0.68644165],
       [-1.29031581, -1.04211089],
       [-0.80497402, -0.50860702],
       [-0.66630494, -1.04211089],
       [-0.87430856, -1.04211089],
       [-0.87430856, -0.68644165],
       [-0.94364311, -1.04211089],
       [-1.01297765,

In [120]:
#separar conjunto de datos
X_train, X_test, y_train, y_test = ml.SplitData(X_norm, y, 0.3)

In [121]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((70, 2), (30, 2), (70,), (30,))

In [122]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0], dtype=int32)

In [123]:
#llamar a adaline
w,loss=ml.Adaline(X_train,y_train,0.01,100)

In [124]:
w,loss

(array([0.49456869, 0.36175943, 0.12820719]),
 [32.69184379102289,
  4.558347587213659,
  1.3444947496475228,
  0.9575449716464733,
  0.9072669533462266,
  0.8989737428493102,
  0.8961678332667814,
  0.8941479388470548,
  0.8922879962523993,
  0.8905012306956845,
  0.8887740085524833,
  0.8871028326438479,
  0.8854856712274574,
  0.8839207483452628,
  0.8824063722795868,
  0.8809409097664036,
  0.8795227808370509,
  0.8781504566320599,
  0.876822457684208,
  0.8755373523137532,
  0.8742937550835808,
  0.8730903253054056,
  0.871925765594381,
  0.8707988204704221,
  0.8697082750047056,
  0.8686529535098859,
  0.8676317182726224,
  0.8666434683270384,
  0.8656871382678024,
  0.864761697101541,
  0.8638661471353555,
  0.8629995229012356,
  0.862160890115213,
  0.8613493446701371,
  0.860564011660983,
  0.8598040444416363,
  0.8590686237121509,
  0.8583569566354814,
  0.8576682759827488,
  0.8570018393061104,
  0.8563569281383488,
  0.8557328472183112,
  0.8551289237413655,
  0.85454450663

In [125]:
y_test

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1], dtype=int32)

In [126]:
y_pred=ml.predict_adaline(X_test,w)

In [127]:
y_pred

array([ 1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,
        1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1])

In [128]:
acc=ml.accuracy(y_test,y_pred)
acc

0.5666666666666667

In [129]:
#llamar perceptron
w,loss=ml.perceptron(X_train,y_train,0.01,10)

In [130]:
w,loss

(array([ 0.01624345,  0.02300294, -0.01595179]),
 [38, 37, 37, 37, 37, 37, 37, 37, 37, 37])

In [131]:
y_pred=ml.predict_perc(X_test,w)

In [132]:
acc=ml.accuracy(y_test,y_pred)
acc

0.5666666666666667

In [133]:
#generar w aleatorio
rgen = np.random.RandomState(60)
w0 = rgen.normal(loc=0.0, scale=0.01,size=1 + X_train.shape[1])

In [134]:
#llamar a regres logit
w,loss=ml.fitLogic(X_train,y_train,w0,0.01,100)

In [135]:
w,loss

(array([-0.02847432,  0.38254105,  0.38986393]),
 array([0.69020946, 0.68558673, 0.68100936, 0.6764769 , 0.67198891,
        0.66754494, 0.66314454, 0.65878729, 0.65447273, 0.65020043,
        0.64596997, 0.64178091, 0.63763282, 0.63352528, 0.62945787,
        0.62543017, 0.62144176, 0.61749223, 0.61358117, 0.60970817,
        0.60587284, 0.60207476, 0.59831355, 0.59458881, 0.59090014,
        0.58724716, 0.58362949, 0.58004674, 0.57649854, 0.57298451,
        0.56950428, 0.56605748, 0.56264375, 0.55926273, 0.55591406,
        0.55259738, 0.54931234, 0.54605861, 0.54283582, 0.53964364,
        0.53648174, 0.53334977, 0.53024741, 0.52717433, 0.52413021,
        0.52111472, 0.51812755, 0.51516838, 0.5122369 , 0.5093328 ,
        0.50645578, 0.50360554, 0.50078178, 0.4979842 , 0.49521252,
        0.49246644, 0.48974567, 0.48704995, 0.48437898, 0.48173249,
        0.4791102 , 0.47651186, 0.47393719, 0.47138592, 0.4688578 ,
        0.46635257, 0.46386997, 0.46140976, 0.45897167, 0.45655547,

In [136]:
y_pred=ml.predictLogic(X_test,w)

In [137]:
acc=ml.accuracy(y_test,y_pred)
acc

1.0